// World Cup 2026 Golden Boot odds (forwards + midfielders), ranked 1 → 100.
// Source: rotowire.com 2026 World Cup Golden Boot odds (american odds).

export type GoldenBootPlayer = {
  rank: number;
  name: string;
  country: string;
  code: string; // FIFA 3-letter code (see components/flag.tsx)
  odds: string; // american odds
};

export const GOLDEN_BOOT_PLAYERS: GoldenBootPlayer[] = [
  { rank: 1, name: "Kylian Mbappé", country: "France", code: "FRA", odds: "+600" },
  { rank: 2, name: "Harry Kane", country: "England", code: "ENG", odds: "+700" },
  { rank: 3, name: "Lionel Messi", country: "Argentina", code: "ARG", odds: "+1200" },
  { rank: 4, name: "Erling Haaland", country: "Norway", code: "NOR", odds: "+1400" },
  { rank: 5, name: "Lamine Yamal", country: "Spain", code: "ESP", odds: "+1800" },
  { rank: 6, name: "Mikel Oyarzabal", country: "Spain", code: "ESP", odds: "+1800" },
  { rank: 7, name: "Cristiano Ronaldo", country: "Portugal", code: "POR", odds: "+2000" },
  { rank: 8, name: "Vinícius Júnior", country: "Brazil", code: "BRA", odds: "+2200" },
  { rank: 9, name: "Lautaro Martínez", country: "Argentina", code: "ARG", odds: "+2500" },
  { rank: 10, name: "Ousmane Dembélé", country: "France", code: "FRA", odds: "+2800" },
  { rank: 11, name: "Romelu Lukaku", country: "Belgium", code: "BEL", odds: "+3000" },
  { rank: 12, name: "Raphinha", country: "Brazil", code: "BRA", odds: "+3000" },
  { rank: 13, name: "Nick Woltemade", country: "Germany", code: "GER", odds: "+3500" },
  { rank: 14, name: "Julián Álvarez", country: "Argentina", code: "ARG", odds: "+3500" },
  { rank: 15, name: "Álvaro Morata", country: "Spain", code: "ESP", odds: "+3500" },
  { rank: 16, name: "Richarlison", country: "Brazil", code: "BRA", odds: "+3500" },
  { rank: 17, name: "João Pedro", country: "Brazil", code: "BRA", odds: "+3500" },
  { rank: 18, name: "Cody Gakpo", country: "Netherlands", code: "NED", odds: "+4000" },
  { rank: 19, name: "Bukayo Saka", country: "England", code: "ENG", odds: "+4000" },
  { rank: 20, name: "Memphis Depay", country: "Netherlands", code: "NED", odds: "+4000" },
  { rank: 21, name: "Ferran Torres", country: "Spain", code: "ESP", odds: "+4000" },
  { rank: 22, name: "Mikel Merino", country: "Spain", code: "ESP", odds: "+4000" },
  { rank: 23, name: "Igor Thiago", country: "Belgium", code: "BEL", odds: "+4000" },
  { rank: 24, name: "Jean-Philippe Mateta", country: "France", code: "FRA", odds: "+5000" },
  { rank: 25, name: "Jude Bellingham", country: "England", code: "ENG", odds: "+5000" },
  { rank: 26, name: "Gonçalo Ramos", country: "Portugal", code: "POR", odds: "+5000" },
  { rank: 27, name: "Florian Wirtz", country: "Germany", code: "GER", odds: "+5000" },
  { rank: 28, name: "Marcus Thuram", country: "France", code: "FRA", odds: "+5000" },
  { rank: 29, name: "Neymar", country: "Brazil", code: "BRA", odds: "+5000" },
  { rank: 30, name: "Bruno Fernandes", country: "Portugal", code: "POR", odds: "+5000" },
  { rank: 31, name: "Luis Díaz", country: "Colombia", code: "COL", odds: "+5000" },
  { rank: 32, name: "Désiré Doué", country: "France", code: "FRA", odds: "+5000" },
  { rank: 33, name: "Mohamed Salah", country: "Egypt", code: "EGY", odds: "+5000" },
  { rank: 34, name: "Kai Havertz", country: "Germany", code: "GER", odds: "+5000" },
  { rank: 35, name: "Dani Olmo", country: "Spain", code: "ESP", odds: "+5000" },
  { rank: 36, name: "Deniz Undav", country: "Germany", code: "GER", odds: "+5000" },
  { rank: 37, name: "Viktor Gyökeres", country: "Sweden", code: "SWE", odds: "+5000" },
  { rank: 38, name: "Enner Valencia", country: "Ecuador", code: "ECU", odds: "+6500" },
  { rank: 39, name: "Donyell Malen", country: "Netherlands", code: "NED", odds: "+6500" },
  { rank: 40, name: "Morgan Rogers", country: "England", code: "ENG", odds: "+6500" },
  { rank: 41, name: "Santiago Giménez", country: "Mexico", code: "MEX", odds: "+6500" },
  { rank: 42, name: "Darwin Núñez", country: "Uruguay", code: "URU", odds: "+6500" },
  { rank: 43, name: "Eberechi Eze", country: "England", code: "ENG", odds: "+6500" },
  { rank: 44, name: "Loïs Openda", country: "Belgium", code: "BEL", odds: "+6500" },
  { rank: 45, name: "Jamal Musiala", country: "Germany", code: "GER", odds: "+6500" },
  { rank: 46, name: "Leandro Trossard", country: "Belgium", code: "BEL", odds: "+6500" },
  { rank: 47, name: "Marcus Rashford", country: "England", code: "ENG", odds: "+6500" },
  { rank: 48, name: "Matheus Cunha", country: "Brazil", code: "BRA", odds: "+6500" },
  { rank: 49, name: "Alexander Sørloth", country: "Norway", code: "NOR", odds: "+6500" },
  { rank: 50, name: "Alexander Isak", country: "Sweden", code: "SWE", odds: "+6500" },
  { rank: 51, name: "Folarin Balogun", country: "USA", code: "USA", odds: "+8000" },
  { rank: 52, name: "Kevin De Bruyne", country: "Belgium", code: "BEL", odds: "+8000" },
  { rank: 53, name: "Christian Pulisic", country: "USA", code: "USA", odds: "+8000" },
  { rank: 54, name: "Anthony Gordon", country: "England", code: "ENG", odds: "+8000" },
  { rank: 55, name: "Rafael Leão", country: "Portugal", code: "POR", odds: "+8000" },
  { rank: 56, name: "Jérémy Doku", country: "Belgium", code: "BEL", odds: "+8000" },
  { rank: 57, name: "Sadio Mané", country: "Senegal", code: "SEN", odds: "+8000" },
  { rank: 58, name: "Leroy Sané", country: "Germany", code: "GER", odds: "+8000" },
  { rank: 59, name: "Jhon Durán", country: "Colombia", code: "COL", odds: "+8000" },
  { rank: 60, name: "Raúl Jiménez", country: "Mexico", code: "MEX", odds: "+8000" },
  { rank: 61, name: "Ante Budimir", country: "Croatia", code: "CRO", odds: "+8000" },
  { rank: 62, name: "Brian Brobbey", country: "Netherlands", code: "NED", odds: "+8000" },
  { rank: 63, name: "Christoph Baumgartner", country: "Austria", code: "AUT", odds: "+8000" },
  { rank: 64, name: "Ollie Watkins", country: "England", code: "ENG", odds: "+8000" },
  { rank: 65, name: "Omar Marmoush", country: "Egypt", code: "EGY", odds: "+10000" },
  { rank: 66, name: "Arda Güler", country: "Turkey", code: "TUR", odds: "+10000" },
  { rank: 67, name: "Mohammed Kudus", country: "Ghana", code: "GHA", odds: "+10000" },
  { rank: 68, name: "Nicolas Jackson", country: "Senegal", code: "SEN", odds: "+10000" },
  { rank: 69, name: "Jonathan David", country: "Canada", code: "CAN", odds: "+10000" },
  { rank: 70, name: "Kenan Yıldız", country: "Turkey", code: "TUR", odds: "+10000" },
  { rank: 71, name: "Pedro Neto", country: "Portugal", code: "POR", odds: "+10000" },
  { rank: 72, name: "Haji Wright", country: "USA", code: "USA", odds: "+10000" },
  { rank: 73, name: "Nico Williams", country: "Spain", code: "ESP", odds: "+10000" },
  { rank: 74, name: "Ricardo Pepi", country: "USA", code: "USA", odds: "+10000" },
  { rank: 75, name: "Scott McTominay", country: "Scotland", code: "SCO", odds: "+10000" },
  { rank: 76, name: "Bradley Barcola", country: "France", code: "FRA", odds: "+10000" },
  { rank: 77, name: "Casemiro", country: "Brazil", code: "BRA", odds: "+10000" },
  { rank: 78, name: "Charles De Ketelaere", country: "Belgium", code: "BEL", odds: "+10000" },
  { rank: 79, name: "Gabriel Martinelli", country: "Brazil", code: "BRA", odds: "+10000" },
  { rank: 80, name: "Rayan Cherki", country: "France", code: "FRA", odds: "+10000" },
  { rank: 81, name: "Breel Embolo", country: "Switzerland", code: "SUI", odds: "+12000" },
  { rank: 82, name: "Ismaïla Sarr", country: "Senegal", code: "SEN", odds: "+15000" },
  { rank: 83, name: "Hamza Igamane", country: "Morocco", code: "MAR", odds: "+15000" },
  { rank: 84, name: "Noa Lang", country: "Netherlands", code: "NED", odds: "+15000" },
  { rank: 85, name: "Hirving Lozano", country: "Mexico", code: "MEX", odds: "+15000" },
  { rank: 86, name: "Lee Kang-in", country: "South Korea", code: "KOR", odds: "+15000" },
  { rank: 87, name: "Enzo Fernández", country: "Argentina", code: "ARG", odds: "+15000" },
  { rank: 88, name: "Jørgen Strand Larsen", country: "Norway", code: "NOR", odds: "+15000" },
  { rank: 89, name: "Riyad Mahrez", country: "Algeria", code: "ALG", odds: "+15000" },
  { rank: 90, name: "James Rodríguez", country: "Colombia", code: "COL", odds: "+15000" },
  { rank: 91, name: "Brahim Díaz", country: "Morocco", code: "MAR", odds: "+15000" },
  { rank: 92, name: "Andrej Kramarić", country: "Croatia", code: "CRO", odds: "+15000" },
  { rank: 93, name: "Jhon Arias", country: "Colombia", code: "COL", odds: "+15000" },
  { rank: 94, name: "Ange-Yoan Bonny", country: "Ivory Coast", code: "CIV", odds: "+15000" },
  { rank: 95, name: "Ivan Toney", country: "England", code: "ENG", odds: "+15000" },
  { rank: 96, name: "Julián Quiñones", country: "Mexico", code: "MEX", odds: "+15000" },
  { rank: 97, name: "Pedri", country: "Spain", code: "ESP", odds: "+20000" },
  { rank: 98, name: "Che Adams", country: "Scotland", code: "SCO", odds: "+20000" },
  { rank: 99, name: "Chris Wood", country: "New Zealand", code: "NZL", odds: "+20000" },
  { rank: 100, name: "Oscar Bobb", country: "Norway", code: "NOR", odds: "+20000" },
];
