name = "betwithfriends-api"
main = "src/index.ts"
compatibility_date = "2025-05-01"
compatibility_flags = ["nodejs_compat"]

[vars]
APP_URL = "https://betwithfriends.jerome-ladeveze.workers.dev"

[[d1_databases]]
binding = "DB"
database_name = "betwithfriends"
database_id = "1a9b9a7f-e5dc-4fb4-90f7-f177d332f238"

[triggers]
crons = ["* * * * *"]